name: Node.js Package

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: "@coach-on-tap"
          cache: "yarn"

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          echo "@coach-on-tap:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Bump version
        if: success()
        run: |
          yarn version --patch --message "Bump version to %s [skip ci]"
          git push
          git push --tags
